version: 3.0.{build}
skip_tags: true
image: Visual Studio 2017 Preview
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
before_build:
- cmd: >-
    dotnet restore

    cd "src/Noobot.Console/Configuration/"

    copy "config.default.json" "config.json"

    cd ../../../
build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
after_build:
- cmd: >-
    del %APPVEYOR_BUILD_FOLDER%\src\Noobot.Console\bin\Release\*.pdb

    del %APPVEYOR_BUILD_FOLDER%\src\Noobot.Console\bin\Release\*.xml


    7z a noobot.zip %APPVEYOR_BUILD_FOLDER%\src\Noobot.Console\bin\Release\*
test: off
artifacts:
- path: noobot.zip
deploy:
- provider: GitHub
  auth_token:
    secure: 8t4+xbVlkXA/FY3516ThrMibGxfCT7ZcSwyZw7KNwUlCH08KMPtznY2QphEn1n/z
  artifact: noobot.zip,/.*\.nupkg/
  draft: true
  on:
    branch: master